version: '3'
services:
  julia-app:
    extends:
      file: docker-compose.dev.yml
      service: julia-app
    volumes:
      - ./assets:/app/assets
      - ./src:/app/src
      - ./test:/app/test
      - ./tmp:/app/tmp
      - ./Manifest.toml:/app/Manifest.toml
      - \\wsl.localhost\Ubuntu-18.04\tmp\.X11-unix:/tmp/.X11-unix
      - \\wsl.localhost\Ubuntu-18.04\mnt\wslg:/mnt/wslg
    environment:
      DISPLAY: ":0"
      WAYLAND_DISPLAY: "wayland-0"
      XDG_RUNTIME_DIR: "/mnt/wslg/runtime-dir"
      PULSE_SERVER: "/mnt/wslg/PulseServer"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]