version: '3'
services:
  julia-app:
    build: .
    environment:
      DISPLAY: "host.docker.internal:0"
    volumes:
      - ./assets:/app/assets
      - ./src:/app/src
      - ./test:/app/test
    working_dir: /app