/**
 * Cylinder-based camera calibration via Ceres nonlinear least squares.
 *
 * Minimises the Gauss-Helmert algebraic residuals
 *
 *   r(line, K, R, d)  =  line' * K * R * d
 *
 * over shared intrinsics [fx, fy, cx, cy] and per-view angle-axis rotations,
 * where d is a cylinder-axis direction (point at infinity in 3-D).
 *
 * This is the l_i^T K R d_i = 0 system from equation-systems.jl, cast as
 * lsqnonlin(fun, x0) – a standard Levenberg-Marquardt nonlinear LS solve.
 *
 * Input:  scene_data.json (generated by scripts/generate_ceres_scene.jl)
 * Output: recovered K, R per view; comparison with ground truth.
 */

#include <ceres/ceres.h>
#include <ceres/rotation.h>
#include <nlohmann/json.hpp>

#include <array>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

using json = nlohmann::json;

// ─── Cost functor ─────────────────────────────────────────────────────────────
//
// One residual per (line, cylinder-axis) pair for a given view.
// Intrinsics are shared across views; each view has its own angle-axis.
//
// Variables
//   intrinsics[4]  = [fx, fy, cx, cy]
//   angle_axis[3]  = world-to-camera rotation as Rodrigues vector
//                    (ceres::AngleAxisRotatePoint convention)
//
// Residual
//   r = l[0]*KRd[0] + l[1]*KRd[1] + l[2]*KRd[2]
// where
//   KRd = K * (R * d),  K = [[fx,0,cx],[0,fy,cy],[0,0,1]]

struct CylinderLineCost {
    CylinderLineCost(std::array<double, 3> line, std::array<double, 3> axis)
        : l_(line), d_(axis) {}

    template <typename T>
    bool operator()(const T* const intr,   // [fx, fy, cx, cy]
                    const T* const aa,     // angle-axis [rx, ry, rz]
                    T* residual) const {
        // Rotate cylinder axis from world to camera frame
        const T d_w[3] = {T(d_[0]), T(d_[1]), T(d_[2])};
        T d_c[3];
        ceres::AngleAxisRotatePoint(aa, d_w, d_c);

        // Apply K:  K * d_c,  K = [[fx,0,cx],[0,fy,cy],[0,0,1]]
        T KRd[3];
        KRd[0] = intr[0] * d_c[0] + intr[2] * d_c[2];  // fx*Rd_x + cx*Rd_z
        KRd[1] = intr[1] * d_c[1] + intr[3] * d_c[2];  // fy*Rd_y + cy*Rd_z
        KRd[2] = d_c[2];

        // Dot with line: l' * KRd
        residual[0] = T(l_[0]) * KRd[0] + T(l_[1]) * KRd[1] + T(l_[2]) * KRd[2];
        return true;
    }

    static ceres::CostFunction* Create(std::array<double, 3> line,
                                       std::array<double, 3> axis) {
        return new ceres::AutoDiffCostFunction<CylinderLineCost, 1, 4, 3>(
            new CylinderLineCost(line, axis));
    }

    std::array<double, 3> l_;
    std::array<double, 3> d_;
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

// Angular distance in degrees between two angle-axis vectors
double rotation_error_deg(const double aa_true[3], const double aa_solved[3]) {
    // Column-major 3x3 rotation matrices (R[i + j*3] = R(row i, col j))
    double R_t[9], R_s[9];
    ceres::AngleAxisToRotationMatrix(aa_true,   R_t);
    ceres::AngleAxisToRotationMatrix(aa_solved, R_s);

    // trace(R_t' * R_s) = sum of element-wise products (both stored col-major)
    double tr = 0.0;
    for (int k = 0; k < 9; ++k) tr += R_t[k] * R_s[k];

    double cos_ang = std::max(-1.0, std::min(1.0, (tr - 1.0) / 2.0));
    return std::acos(cos_ang) * 180.0 / M_PI;
}

double rel_err(double solved, double truth) {
    if (truth == 0.0) return std::abs(solved);
    return std::abs((solved - truth) / truth) * 100.0;  // percent
}

// ─── Main ─────────────────────────────────────────────────────────────────────

int main(int argc, char** argv) {
    const std::string json_path = (argc > 1) ? argv[1] : "scene_data.json";

    std::ifstream f(json_path);
    if (!f.is_open()) {
        std::cerr << "Cannot open " << json_path << "\n";
        return 1;
    }
    json data = json::parse(f);

    const int n_views = data["n_views"];

    // ── Parameter blocks ──────────────────────────────────────────────────────
    double intr[4] = {
        data["start"]["intrinsics"]["fx"],
        data["start"]["intrinsics"]["fy"],
        data["start"]["intrinsics"]["cx"],
        data["start"]["intrinsics"]["cy"]
    };
    std::vector<std::array<double, 3>> aa(n_views);
    for (int v = 0; v < n_views; ++v) {
        auto& src = data["start"]["rotations"][v]["angle_axis"];
        aa[v] = {src[0], src[1], src[2]};
    }

    // ── Build problem ─────────────────────────────────────────────────────────
    ceres::Problem problem;

    for (auto& entry : data["residuals"]) {
        int v = entry["view"];
        std::array<double,3> line = {entry["line"][0], entry["line"][1], entry["line"][2]};
        std::array<double,3> axis = {entry["axis"][0], entry["axis"][1], entry["axis"][2]};

        problem.AddResidualBlock(
            CylinderLineCost::Create(line, axis),
            nullptr,          // no robust loss
            intr, aa[v].data()
        );
    }

    // ── Solve ─────────────────────────────────────────────────────────────────
    ceres::Solver::Options opts;
    opts.linear_solver_type        = ceres::DENSE_QR;
    opts.minimizer_progress_to_stdout = true;
    opts.max_num_iterations        = 500;
    opts.function_tolerance        = 1e-14;
    opts.gradient_tolerance        = 1e-14;
    opts.parameter_tolerance       = 1e-14;

    ceres::Solver::Summary summary;
    ceres::Solve(opts, &problem, &summary);

    std::cout << "\n" << summary.BriefReport() << "\n\n";

    // ── Report ────────────────────────────────────────────────────────────────
    const double true_fx = data["true"]["intrinsics"]["fx"];
    const double true_fy = data["true"]["intrinsics"]["fy"];
    const double true_cx = data["true"]["intrinsics"]["cx"];
    const double true_cy = data["true"]["intrinsics"]["cy"];
    const double start_fx = data["start"]["intrinsics"]["fx"];
    const double start_fy = data["start"]["intrinsics"]["fy"];
    const double start_cx = data["start"]["intrinsics"]["cx"];
    const double start_cy = data["start"]["intrinsics"]["cy"];

    auto W = std::setw(10);
    std::cout << std::fixed << std::setprecision(4);
    std::cout << "═══════════════════════════════════════════════════════════\n";
    std::cout << "  Intrinsic parameters\n";
    std::cout << "───────────────────────────────────────────────────────────\n";
    std::cout << W << "param" << W << "true" << W << "start"
              << W << "solved" << W << "err (%)\n";
    std::cout << "───────────────────────────────────────────────────────────\n";

    auto row = [&](const char* name, double truth, double start, double solved) {
        std::cout << W << name << W << truth << W << start
                  << W << solved << W << rel_err(solved, truth) << "%\n";
    };
    row("fx", true_fx, start_fx, intr[0]);
    row("fy", true_fy, start_fy, intr[1]);
    row("cx", true_cx, start_cx, intr[2]);
    row("cy", true_cy, start_cy, intr[3]);

    std::cout << "───────────────────────────────────────────────────────────\n";
    std::cout << "  Rotation errors (angular distance in degrees)\n";
    std::cout << "───────────────────────────────────────────────────────────\n";
    std::cout << W << "view" << W << "start→true" << W << "solved→true\n";
    std::cout << "───────────────────────────────────────────────────────────\n";

    for (int v = 0; v < n_views; ++v) {
        auto& t_src  = data["true"]["rotations"][v]["angle_axis"];
        auto& s_src  = data["start"]["rotations"][v]["angle_axis"];
        double aa_true[3]  = {t_src[0], t_src[1], t_src[2]};
        double aa_start[3] = {s_src[0], s_src[1], s_src[2]};

        double err_start  = rotation_error_deg(aa_true, aa_start);
        double err_solved = rotation_error_deg(aa_true, aa[v].data());

        std::cout << W << v << W << err_start << "°"
                  << W << err_solved << "°\n";
    }
    std::cout << "═══════════════════════════════════════════════════════════\n";

    return 0;
}
